//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./hello_types');
//HELPER FUNCTIONS AND STRUCTURES

var TimesTwo_dbl_args = function(args) {
  this.val = null;
  if (args) {
    if (args.val !== undefined && args.val !== null) {
      this.val = args.val;
    }
  }
};
TimesTwo_dbl_args.prototype = {};
TimesTwo_dbl_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.val = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TimesTwo_dbl_args.prototype.write = function(output) {
  output.writeStructBegin('TimesTwo_dbl_args');
  if (this.val !== null && this.val !== undefined) {
    output.writeFieldBegin('val', Thrift.Type.I64, 1);
    output.writeI64(this.val);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TimesTwo_dbl_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
TimesTwo_dbl_result.prototype = {};
TimesTwo_dbl_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.I64) {
        this.success = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TimesTwo_dbl_result.prototype.write = function(output) {
  output.writeStructBegin('TimesTwo_dbl_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.I64, 0);
    output.writeI64(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TimesTwoClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
TimesTwoClient.prototype = {};
TimesTwoClient.prototype.seqid = function() { return this._seqid; };
TimesTwoClient.prototype.new_seqid = function() { return this._seqid += 1; };
TimesTwoClient.prototype.dbl = function(val, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_dbl(val);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_dbl(val);
  }
};

TimesTwoClient.prototype.send_dbl = function(val) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('dbl', Thrift.MessageType.CALL, this.seqid());
  var params = {
    val: val
  };
  var args = new TimesTwo_dbl_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

TimesTwoClient.prototype.recv_dbl = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new TimesTwo_dbl_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('dbl failed: unknown result');
};
var TimesTwoProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
TimesTwoProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
TimesTwoProcessor.prototype.process_dbl = function(seqid, input, output) {
  var args = new TimesTwo_dbl_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.dbl.length === 1) {
    Q.fcall(this._handler.dbl.bind(this._handler), args.val)
      .then(function(result) {
        var result_obj = new TimesTwo_dbl_result({success: result});
        output.writeMessageBegin("dbl", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("dbl", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.dbl(args.val, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new TimesTwo_dbl_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("dbl", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("dbl", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
